"""
Default parameters for every generator and global app settings.
"""

APP = {
    "preview_size": (512, 512),
    "export_size":  (4096, 4096),
    "max_palette_colors": 10,
    "default_palette_colors": 5,
    "thread_pool_workers": 4,
}

# ── transparent_bg is available on every generator ────────────────────────────
# When True the first palette colour becomes fully transparent (alpha=0).
# Useful when using the generator as a second layer.

_DIGITALIZE_CONTROL = {
    "digitalize_level": {
        "default": 0, "min": 0, "max": 6, "step": 1,
        "label": "Digitalize level",
        "tip": (
            "Pixelate the output by subsampling then upscaling with no interpolation. "
            "0=off, 1=2×2 blocks, 2=4×4, …, k=2^k×2^k blocks. "
            "Palette colours are preserved exactly (no blending)."
        ),
    },
    "digitalize_diagonal": {
        "default": False, "type": "bool",
        "label": "Diagonal digitalize (45°)",
        "tip": (
            "Tile 3×3 → rotate 45° → subsample → rotate back → crop centre. "
            "Produces diagonal pixel blocks while remaining seamlessly tileable. "
            "Has no effect when Digitalize level is 0."
        ),
        "evolvable": False,
    },
}

_TRANSPARENT_BG = {
    "transparent_bg": {
        "default": False, "type": "bool",
        "label": "Transparent background",
        "tip": "First palette colour → transparent. Use when layering over another generator.",
        "evolvable": False,
    }
}

_BG_CONTROLS = {
    "bg_color_idx": {
        "default": 0, "min": 0, "max": 9, "step": 1,
        "label": "Background colour index",
        "tip": "Which palette colour is the background. Used for canvas fill and optionally for transparency.",
    },
    "exclude_bg_from_elements": {
        "default": False, "type": "bool",
        "label": "Exclude bg colour from elements",
        "tip": "When checked, generated elements (shapes, cells, stripes) never use the background colour — it is reserved for the canvas fill.",
    },
}


GENERATORS = {
    # ── Blur-Sharp ────────────────────────────────────────────────────────────
    "blur_sharp": {
        "sigma_x":      {"default": 4.0,  "min": 0.5, "max": 30.0, "step": 0.5,
                         "label": "Blur σ X",
                         "tip": "Blur radius along the first axis (pre-rotation). Much larger than σY → stripes; equal → spots."},
        "sigma_y":      {"default": 4.0,  "min": 0.5, "max": 30.0, "step": 0.5,
                         "label": "Blur σ Y",
                         "tip": "Blur radius along the second axis (pre-rotation)."},
        "blur_angle":   {"default": 0.0,  "min": -90.0, "max": 90.0, "step": 5.0,
                         "label": "Blur angle (°)",
                         "tip": "Rotate the blur direction. 0=axis-aligned, 45=diagonal stripes, etc."},
        "iterations":   {"default": 12,   "min": 1,   "max": 25,   "step": 1,
                         "label": "Iterations",
                         "tip": "Rounds of blur+sharpen. 8–15 is typical; pattern stabilises quickly."},
        "sharpen_amt":  {"default": 4.0,  "min": 0.5, "max": 12.0, "step": 0.5,
                         "label": "Sharpen amount",
                         "tip": "Unsharp-mask strength. Higher → harder edges, more contrasty bands."},
        "sharpen_sigma":{"default": 2.0,  "min": 0.5, "max": 8.0,  "step": 0.5,
                         "label": "Sharpen radius",
                         "tip": "Unsharp-mask blur radius. Keep at 1–3 for crisp edges."},
        "noise_density":   {"default": 0.15,    "min": 0.01,   "max": 1,   "step": 0.01,
                         "label": "Noise density",
                         "tip": "Density of initial noise. Low → sparse cells; medium → stripes and coral."},
        "noise_amp":    {"default": 0.5,  "min": 0.05,"max": 1.0,  "step": 0.05,
                         "label": "Noise amplitude",
                         "tip": "Initial noise strength. Low → subtle spots; high → connected channels."},
        "noise_mode":   {"default": "uniform", "options": ["uniform", "binary"],
                         "label": "Grey noise or black and white",
                         "tip": "Uniform noise for smoother outputs."},
        "work_size":    {"default": 256,  "min": 64,  "max": 512,  "step": 32,
                         "label": "Work size (px)",
                         "tip": "Internal simulation resolution. Result is upscaled with optional smoothing."},
        "post_blur":    {"default": 1.0,  "min": 0.0, "max": 6.0,  "step": 0.5,
                         "label": "Post-upscale blur",
                         "tip": "Gaussian smoothing after upscaling. 0 = none (pixelated); 1–2 = smooth."},
        "color_mode":   {"default": "threshold", "options": ["threshold", "gradient"],
                         "label": "Colour bands",
                         "tip": "threshold = sharp N-band quantisation; gradient = smooth interpolation."},
        "seed":         {"default": 42,   "min": 0,   "max": 99999, "step": 1,
                         "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Reaction-Diffusion (Gray-Scott) ───────────────────────────────────────
    "reaction_diffusion": {
        "preset":      {"default": "Labyrinth",
                        "options": ["Spots","Labyrinth","Stripes","Coral","Mitosis","Custom"],
                        "label": "Pattern preset",
                        "tip": "Sets feed+kill. Custom lets you edit them directly.",
                        "evolvable": False},
        "Du":          {"default": 0.16,  "min": 0.05, "max": 0.5,  "step": 0.01,
                        "label": "Du (activator diff.)",
                        "tip": "Keep > Dv. Usually 0.10–0.20."},
        "Dv":          {"default": 0.08,  "min": 0.01, "max": 0.3,  "step": 0.01,
                        "label": "Dv (inhibitor diff.)",
                        "tip": "Keep < Du. Usually 0.04–0.10."},
        "feed":        {"default": 0.037, "min": 0.01, "max": 0.10, "step": 0.001,
                        "label": "Feed rate",
                        "tip": "Spots≈0.035, Labyrinth≈0.037, Stripes≈0.060, Coral≈0.062."},
        "kill":        {"default": 0.060, "min": 0.04, "max": 0.07, "step": 0.001,
                        "label": "Kill rate",
                        "tip": "Spots≈0.065, Labyrinth≈0.060, Stripes≈0.062, Coral≈0.061."},
        "time_steps":  {"default": 3000,  "min": 500,  "max": 15000,"step": 500,
                        "label": "Time steps",
                        "tip": "2000–5000 is usually enough. More → more evolved pattern."},
        "work_size":   {"default": 200,   "min": 64,   "max": 384,  "step": 32,
                        "label": "Work resolution",
                        "tip": "Simulation size. Lower = faster. Result upscaled."},
        "post_blur":   {"default": 1.0,   "min": 0.0,  "max": 6.0,  "step": 0.5,
                        "label": "Post-upscale blur",
                        "tip": "Smooths pixelation after upscaling. 0 = keep pixelated look."},
        "noise_scale": {"default": 0.05,  "min": 0.01, "max": 0.3,  "step": 0.01,
                        "label": "Seed noise",
                        "tip": "Initial perturbation amplitude."},
        "anisotropy":  {"default": 1.0,   "min": 0.2,  "max": 3.0,  "step": 0.1,
                        "label": "Anisotropy X/Y",
                        "tip": ">1 stretches pattern horizontally; <1 vertically."},
        "seed":        {"default": 42,    "min": 0,    "max": 99999, "step": 1,
                        "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Procedural Noise ──────────────────────────────────────────────────────
    "procedural_noise": {
        "noise_type":  {"default": "seamless_perlin",
                        "options": ["seamless_perlin", "seamless_simplex"],
                        "label": "Noise type",
                        "tip": "seamless_perlin = standard Perlin with toroidal repeat; seamless_simplex = 4D torus simplex (no linear artefacts, no repeat boundary)."},
        "octaves":     {"default": 6,    "min": 1,   "max": 12,   "step": 1,
                        "label": "Octaves",            "tip": "Layers of detail."},
        "persistence": {"default": 0.5,  "min": 0.1, "max": 1.0,  "step": 0.05,
                        "label": "Persistence",        "tip": "How much each octave contributes."},
        "lacunarity":  {"default": 2,  "min": 1, "max": 5,  "step": 1,
                        "label": "Lacunarity (integer)",
                        "tip": "Integer values only — prevents octave beat-frequency artefacts (diagonal stripes / grid lines)."},
        "periods":     {"default": 3,    "min": 1,   "max": 12,   "step": 1,
                        "label": "Tile periods",
                        "tip": "Noise periods across canvas. Low=large blobs, high=fine texture."},
        "turbulence":  {"default": 0.0,  "min": 0.0, "max": 1.0,  "step": 0.05,
                        "label": "Turbulence",         "tip": "Coordinate warping for organic distortion."},
        "color_mode":  {"default": "threshold", "options": ["threshold", "voronoi"],
                        "label": "Color assignment",
                        "tip": "threshold = equal bands; voronoi = nearest-centroid."},
        "seed":        {"default": 42,   "min": 0,   "max": 99999, "step": 1,
                        "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── L-System ──────────────────────────────────────────────────────────────
    "l_system": {
        "axiom":         {"default": "F",  "type": "str",
                          "label": "Axiom",              "tip": "Starting string."},
        "rules":         {"default": "F->FF+[+F-F-F]-[-F+F+F]", "type": "str",
                          "label": "Rules (semicolon-sep)",
                          "tip": "e.g.  F->FF+X ; X->F-X"},
        "angle":         {"default": 25.0, "min": 5.0, "max": 90.0, "step": 0.5,
                          "label": "Base angle (°)",
                          "tip": "Central turning angle for +/– commands."},
        "angle_var":     {"default": 8.0,  "min": 0.0, "max": 45.0, "step": 0.5,
                          "label": "Angle variation (°)",
                          "tip": "Each tree gets base_angle ± random(angle_var)."},
        "iterations":    {"default": 4,    "min": 1,   "max": 7,    "step": 1,
                          "label": "Iterations",
                          "tip": "More = finer detail, much slower."},
        "num_trees":     {"default": 9,    "min": 1,   "max": 50,   "step": 1,
                          "label": "Number of trees",
                          "tip": "Trees placed at random positions across the canvas."},
        "step_min":      {"default": 3,    "min": 1,   "max": 40,   "step": 1,
                          "label": "Step size min (px)", "tip": "Shortest turtle step."},
        "step_max":      {"default": 8,    "min": 1,   "max": 60,   "step": 1,
                          "label": "Step size max (px)", "tip": "Longest turtle step."},
        "width_min":     {"default": 1,    "min": 1,   "max": 8,    "step": 1,
                          "label": "Line width min (px)","tip": "Thinnest stroke."},
        "width_max":     {"default": 2,    "min": 1,   "max": 12,   "step": 1,
                          "label": "Line width max (px)","tip": "Thickest stroke."},
        "color_per_tree":{"default": True, "type": "bool",
                          "label": "Per-tree colour",
                          "tip": "Each tree picks a random palette colour."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999, "step": 1,
                          "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Recursive Fractal ─────────────────────────────────────────────────────
    "recursive_fractal": {
        "depth":          {"default": 3,   "min": 1, "max": 5,   "step": 1,
                           "label": "Recursion depth",
                           "tip": "Voronoi levels. >3 can be slow; capped at 3 during evolution."},
        "base_seeds":     {"default": 6,   "min": 1, "max": 16,  "step": 1,
                           "label": "Base seed count",   "tip": "Coarsest level cell count."},
        "seed_multiplier":{"default": 3,   "min": 2, "max": 5,   "step": 1,
                           "label": "Seed multiplier",
                           "tip": "Each finer level multiplies seed count. Capped at 800/level."},
        "level_opacity":  {"default": 0.55,"min": 0.1,"max": 0.9,"step": 0.05,
                           "label": "Level blend opacity",
                           "tip": "How strongly finer levels show through coarser ones."},
        "edge_sharpness": {"default": 0.0, "min": 0.0,"max": 20.0,"step": 0.5,
                           "label": "Edge sharpening",   "tip": "Sharpens cell boundaries. 0=off."},
        "warp_strength":  {"default": 0.0, "min": 0.0,"max": 2.0, "step": 0.1,
                           "label": "Organic warp",
                           "tip": "Perlin domain warp applied before Voronoi distance. "
                                  "0=angular cells, 0.5-1.5=giraffe-patch organic blobs."},
        "warp_scale":     {"default": 0.3, "min": 0.05,"max":1.0, "step": 0.05,
                           "label": "Warp scale",
                           "tip": "Spatial frequency of the organic warp. Low=large sweeping distortion."},
        "outline_width":  {"default": 0,   "min": 0,  "max": 16,  "step": 1,
                           "label": "Cell outline (px)", "tip": "Dark border between cells. 0=none."},
        "seed":           {"default": 42,  "min": 0,  "max": 99999,"step": 1,
                           "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Urban Geometric ─────────────────────────────────────────────────────
    "urban_geometric": {
        "primitive":      {"default": "hexagon",
                           "options": ["hexagon","triangle","offset_grid","diamond"],
                           "label": "Primitive shape",    "tip": "Base tile geometry."},
        "placement_mode": {"default": "tiled",
                           "options": ["tiled", "random", "field_driven"],
                           "label": "Placement mode",
                           "tip": "tiled=grid+jitter (original); random=scatter N shapes; field_driven=density+orientation field clustering.",
                           "evolvable": False},
        # ── tiled-mode params ────────────────────────────────────────────────
        "cell_size":     {"default": 40,   "min": 10,  "max": 200, "step": 5,
                          "label": "Cell size (px)",
                          "tip": "[tiled] Approximate tile size. Grid snapped for seamless tiling."},
        "size_count":    {"default": 2,    "min": 1,   "max": 5,   "step": 1,
                          "label": "Size variants",
                          "tip": "[tiled] Number of distinct interleaved tile sizes."},
        "size_ratio":    {"default": 0.5,  "min": 0.2, "max": 0.9, "step": 0.05,
                          "label": "Size ratio",
                          "tip": "[tiled] Each smaller size = previous × ratio."},
        "jitter":        {"default": 0.12, "min": 0.0, "max": 0.5, "step": 0.01,
                          "label": "Jitter",             "tip": "[tiled] Random offset per cell centre."},
        # ── random / field_driven shared params ──────────────────────────────
        "num_shapes":    {"default": 60,   "min": 5,   "max": 500, "step": 5,
                          "label": "Shape count",
                          "tip": "[random/field] Total number of shapes to scatter."},
        "scale_min":     {"default": 0.05, "min": 0.01,"max": 0.5, "step": 0.01,
                          "label": "Scale min",
                          "tip": "[random/field] Smallest shape relative to canvas."},
        "scale_max":     {"default": 0.20, "min": 0.02,"max": 1.0, "step": 0.01,
                          "label": "Scale max",
                          "tip": "[random/field] Largest shape relative to canvas."},
        "rotation_range":{"default": 180,  "min": 0,   "max": 180, "step": 5,
                          "label": "Rotation range (°)",
                          "tip": "[random/field] ±degrees of random rotation."},
        # ── field_driven params ───────────────────────────────────────────────
        "field_scale":      {"default": 0.25, "min": 0.05, "max": 1.0, "step": 0.05,
                             "label": "Field scale",
                             "tip": "[field] Spatial scale of density/orientation fields."},
        "density_contrast": {"default": 0.7,  "min": 0.0,  "max": 1.0, "step": 0.05,
                             "label": "Density contrast",
                             "tip": "[field] 0=uniform scatter, 1=tight clusters."},
        "orient_coherence": {"default": 0.6,  "min": 0.0,  "max": 1.0, "step": 0.05,
                             "label": "Orientation coherence",
                             "tip": "[field] 0=fully random rotation, 1=fully field-aligned."},
        "outline_width": {"default": 0,    "min": 0,   "max": 4,   "step": 1,
                          "label": "Outline width (px)", "tip": "0 = no outline."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Collage ─────────────────────────────────────────────────────────────────────────────
    "collage": {
        "shape_folder":      {"default": "", "type": "folder",
                              "label": "Shape folder (PNG/JPG)",
                              "tip": "Folder of PNG/JPG files. Empty = built-in procedural shapes."},
        "count":             {"default": 40,   "min": 5,   "max": 300, "step": 5,
                              "label": "Shape count",        "tip": "Number of placed shapes."},
        "scale_min":         {"default": 0.05, "min": 0.01,"max": 0.5, "step": 0.01,
                              "label": "Scale min",
                              "tip": "Smallest shape relative to canvas width."},
        "scale_max":         {"default": 0.25, "min": 0.05,"max": 1.0, "step": 0.01,
                              "label": "Scale max",
                              "tip": "Largest shape relative to canvas width."},
        "rotation_range":    {"default": 180,  "min": 0,   "max": 180, "step": 5,
                              "label": "Rotation range (°)", "tip": "±degrees of random rotation."},
        "blend_mode":        {"default": "normal",
                              "options": ["normal","multiply","screen","overlay"],
                              "label": "Blend mode",         "tip": "How shapes blend onto canvas."},
        "tint_strength":     {"default": 0.8,  "min": 0.0, "max": 1.0, "step": 0.05,
                              "label": "Tint strength",
                              "tip": "0 = keep original colours; 1 = fully tinted to palette."},
        "bg_color_idx":      {"default": 0,    "min": 0,   "max": 9,   "step": 1,
                              "label": "Background colour index",
                              "tip": "This palette colour fills the canvas. Shapes never tinted to it."},
        "placement_mode":    {"default": "random",
                              "options": ["random", "field_driven", "grid", "triangle_grid"],
                              "label": "Placement mode",
                              "tip": "random=scatter; field_driven=Perlin-clustered; "
                                     "grid=regular square grid; triangle_grid=triangular tiling.",
                              "evolvable": False},
        "grid_cell_size":    {"default": 60,   "min": 8,   "max": 300, "step": 4,
                              "label": "Grid cell size (px)",
                              "tip": "[grid / triangle_grid] Size of each tiling cell."},
        "use_fields":        {"default": False, "type": "bool",
                              "label": "Field-driven placement",
                              "tip": "Use spatial fields to cluster shapes and align them locally (random mode only)."},
        "field_scale":       {"default": 0.25, "min": 0.05, "max": 1.0, "step": 0.05,
                              "label": "Field scale",
                              "tip": "Spatial scale of density/orientation/scale fields."},
        "density_contrast":  {"default": 0.7,  "min": 0.0,  "max": 1.0, "step": 0.05,
                              "label": "Density contrast",
                              "tip": "0=uniform placement, 1=tight clusters with empty gaps."},
        "orient_coherence":  {"default": 0.6,  "min": 0.0,  "max": 1.0, "step": 0.05,
                              "label": "Orientation coherence",
                              "tip": "0=fully random rotation, 1=fully field-aligned."},
        "scale_variation":   {"default": 0.5,  "min": 0.0,  "max": 1.0, "step": 0.05,
                              "label": "Scale field variation",
                              "tip": "How much the scale field modulates shape size."},
        "seed":              {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                              "label": "Random seed",        "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Plaid ────────────────────────────────────────────────────────────────────────────────────────
    "plaid": {
        "angle":         {"default": "0",
                          "options": ["0", "45"],
                          "label": "Grid angle",
                          "tip": "0° = axis-aligned H+V tartan. 45° = two crossing diagonals."},
        "n_base":        {"default": 4,    "min": 1,   "max": 24,  "step": 1,
                          "label": "Coarse stripe count",
                          "tip": "Integer number of coarse stripe periods across the canvas. Seamless for any integer value."},
        "num_scales":    {"default": 3,    "min": 1,   "max": 6,   "step": 1,
                          "label": "Octave count",
                          "tip": "How many nested stripe scales. 1=simple grid, 3=tartan-like, 5+=complex weave."},
        "scale_factor":  {"default": 2,    "min": 2,   "max": 5,   "step": 1,
                          "label": "Scale factor (integer)",
                          "tip": "Each finer octave has scale_factor× more periods. Integer guarantees seamless nesting."},
        "h_weight":      {"default": 0.5,  "min": 0.1, "max": 0.9, "step": 0.05,
                          "label": "H/V balance",
                          "tip": "0=only axis-A stripes, 0.5=symmetric plaid, 1=only axis-B stripes."},
        "edge_softness": {"default": 0.15, "min": 0.0, "max": 0.45,"step": 0.01,
                          "label": "Edge softness",
                          "tip": "0=hard crisp edges (graphic tartan), 0.45=very soft colour wash."},
        "blend_mode":    {"default": "normal",
                          "options": ["normal", "multiply", "screen", "overlay"],
                          "label": "Blend mode",
                          "tip": "How stripe layers combine. multiply=dark crossings, screen=bright, overlay=high contrast."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Dazzle ────────────────────────────────────────────────────────────────────────────────────────
    "dazzle": {
        "num_zones":         {"default": 12,   "min": 1,   "max": 60,  "step": 1,
                              "label": "Zone count",
                              "tip": "Number of toroidal Voronoi zones. More = smaller, more fragmented areas."},
        "stripe_density":    {"default": 8,    "min": 0,   "max": 30,  "step": 1,
                              "label": "Stripe density",
                              "tip": "Base number of stripe periods per zone. Higher = finer stripes."},
        "density_variation": {"default": 0.5,  "min": 0.0, "max": 1.0, "step": 0.05,
                              "label": "Density variation",
                              "tip": "How much stripe density varies between zones. 0=all same, 1=high variation."},
        "directions":        {"default": "mixed",
                              "options": ["mixed", "striped", "diagonal"],
                              "label": "Stripe directions",
                              "tip": "mixed=all 4 directions; striped=H+V only; diagonal=diag only."},
        "outline_width":     {"default": 2,    "min": 0,   "max": 32,   "step": 1,
                              "label": "Zone outline (px)",
                              "tip": "Border drawn between zones. 0=none."},
        "high_contrast":     {"default": True, "type": "bool",
                              "label": "Force high contrast",
                              "tip": "Alternate palette halves between zone colour pairs for max contrast."},
        "warp_strength":     {"default": 0.0,  "min": 0.0, "max": 2.0,  "step": 0.1,
                              "label": "Organic warp",
                              "tip": "Perlin warp applied before Voronoi, rounding zones into giraffe-patch shapes. 0=angular."},
        "warp_scale":        {"default": 0.3,  "min": 0.05,"max": 1.0,  "step": 0.05,
                              "label": "Warp scale",
                              "tip": "Spatial frequency of the organic warp field."},
        "seed":              {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                              "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Digital Camo ──────────────────────────────────────────────────────────
    "digital_camo": {
        "cell_size":     {"default": 12,   "min": 2,   "max": 64,  "step": 1,
                          "label": "Cell size (px)",
                          "tip": "Pixel block size. Larger = coarser MARPAT-style blocks."},
        "noise_periods": {"default": 4,    "min": 1,   "max": 12,  "step": 1,
                          "label": "Noise periods",
                          "tip": "Base noise frequency. Low=large colour regions, high=fine noise."},
        "num_levels":    {"default": 2,    "min": 1,   "max": 4,   "step": 1,
                          "label": "Levels",
                          "tip": "Multi-scale pixelation levels. 1=single block size; 2-3=nested blocks like MARPAT."},
        "level_scale":   {"default": 2.5,  "min": 1.5, "max": 5.0, "step": 0.5,
                          "label": "Level scale factor",
                          "tip": "How much larger each successive level is. 2.5 = each level is 2.5× coarser."},
        "angle":         {"default": "0", "options": ["0", "45"],
                          "label": "Pixel grid angle",
                          "tip": "0=axis-aligned blocks (seamless). 45=diagonal pixel grid via 3×3 tile (also seamless).",
                          "evolvable": False},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_TRANSPARENT_BG,
    },

    # ── Argyle ────────────────────────────────────────────────────────────────
    # Argyle is a special case of the plaid generator with acute diamond angles.
    "argyle": {
        "diamond_ratio": {"default": "1:1 (square)",
                          "options": ["4:1 (tall x4)", "3:1 (tall x3)", "2:1 (tall x2)",
                                      "1:1 (square)", "1:2 (wide x2)", "1:3 (wide x3)", "1:4 (wide x4)"],
                          "label": "Diamond shape (across:down)",
                          "tip": ("Ratio of diamonds-across to diamonds-down. "
                                  "1:1=square, 2:1=twice as many across (wide), 1:2=twice as many down (tall). "
                                  "All ratios tile a square canvas seamlessly."),
                          "evolvable": False},
        "n_base":        {"default": 4,    "min": 1,   "max": 24,  "step": 1,
                          "label": "Diamond count",
                          "tip": ("Approximate number of diamonds across the canvas. "
                                  "The actual count may be slightly adjusted (up, never below) "
                                  "to guarantee seamless colour with the current palette size.")},
        "num_scales":    {"default": 1,    "min": 1,   "max": 4,   "step": 1,
                          "label": "Overlay scales",
                          "tip": "Number of nested argyle overlays (1=single, 2+=adds finer grid lines)."},
        "edge_softness": {"default": 0.15, "min": 0.0, "max": 0.49,"step": 0.01,
                          "label": "Edge softness",
                          "tip": ("0=crisp hard-edge diamonds. Higher values blend the edges. "
                                  "At 0.49 the diamonds almost fully overlap (very soft gradient).")},
        "show_lines":    {"default": True, "type": "bool",
                          "label": "Overlay crossing lines",
                          "tip": "Draw the characteristic thin crossing lines inside the diamonds."},
        "line_width":    {"default": 0.03, "min": 0.005,"max": 0.15,"step": 0.005,
                          "label": "Line width (rel.)",
                          "tip": "Thickness of overlay lines relative to diamond period."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── African Pattern ───────────────────────────────────────────────────────
    "african_pattern": {
        "motif":         {"default": "kente",
                          "options": ["kente", "kuba", "adinkra", "mudcloth"],
                          "label": "Motif style",
                          "tip": ("kente=interlocked horizontal bands with geometric fills; "
                                  "kuba=interlaced square-spiral / guilloche cells; "
                                  "adinkra=symbol stamps on grid; "
                                  "mudcloth=bold opposing-line mud-cloth grid."),
                          "evolvable": False},
        "cell_size":     {"default": 48,   "min": 16,  "max": 160, "step": 4,
                          "label": "Cell size (px)",
                          "tip": "Base tile size for the motif grid."},
        "band_height":   {"default": 32,   "min": 8,   "max": 128, "step": 4,
                          "label": "Band height (px)",
                          "tip": "[kente/mudcloth] Height of each horizontal colour band."},
        "fill_density":  {"default": 0.5,  "min": 0.1, "max": 1.0, "step": 0.05,
                          "label": "Fill density",
                          "tip": "Proportion of cells / area filled with pattern elements."},
        "line_width":    {"default": 2,    "min": 1,   "max": 8,   "step": 1,
                          "label": "Line width (px)",
                          "tip": "Stroke width for all drawn lines and borders."},
        "rotation":      {"default": 0,    "min": 0,   "max": 3,   "step": 1,
                          "label": "Rotation steps (×90°)",
                          "tip": "Rotate the entire pattern in 90° steps."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },

    # ── Japanese Pattern ──────────────────────────────────────────────────────
    "japanese_pattern": {
        "motif":         {"default": "seigaiha",
                          "options": ["seigaiha", "asanoha", "shippo", "sayagata", "yagasuri"],
                          "label": "Motif style",
                          "tip": ("seigaiha=overlapping scales (wave); "
                                  "asanoha=six-pointed star from equilateral triangles; "
                                  "shippo=interlocked circles (seven treasures); "
                                  "sayagata=interlocked key-fret meanders; "
                                  "yagasuri=arrow-feather chevrons."),
                          "evolvable": False},
        "cell_size":     {"default": 48,   "min": 12,  "max": 160, "step": 4,
                          "label": "Cell size (px)",
                          "tip": "Diameter / repeat unit of each motif element."},
        "line_width":    {"default": 2,    "min": 1,   "max": 8,   "step": 1,
                          "label": "Line width (px)",
                          "tip": "Stroke width for all outlines."},
        "fill_alt":      {"default": True, "type": "bool",
                          "label": "Alternate fill colours",
                          "tip": "Fill alternating elements with different palette colours for contrast."},
        "rotation":      {"default": 0,    "min": 0,   "max": 3,   "step": 1,
                          "label": "Rotation steps (×90°)",
                          "tip": "Rotate the entire pattern in 90° steps."},
        "seed":          {"default": 42,   "min": 0,   "max": 99999,"step": 1,
                          "label": "Random seed",       "tip": "Reproducibility."},
        **_BG_CONTROLS,
        **_DIGITALIZE_CONTROL,
        **_TRANSPARENT_BG,
    },
}

# Gray-Scott presets: (feed, kill)
RD_PRESETS = {
    "Spots":     (0.035, 0.065),
    "Labyrinth": (0.037, 0.060),
    "Stripes":   (0.060, 0.062),
    "Coral":     (0.062, 0.061),
    "Mitosis":   (0.028, 0.062),
    "Custom":    None,
}

EVOLUTION = {
    "population_size":    16,
    "generations":        10,
    "mutation_strength":  0.15,
    "crossover_rate":     0.5,
    "moth_size_min":      80,
    "moth_size_max":      160,
    "max_fractal_depth":  3,       # depth cap when generating in evo worker
    "individual_timeout": 30.0,    # seconds per individual before abort
    "fitness_weights": {
        "color":      0.4,
        "texture":    0.35,
        "disruption": 0.25,
    },
    "pso": {"c1": 1.5, "c2": 1.5, "w": 0.7},
}

BLEND_MODES = ["normal", "multiply", "screen", "overlay", "soft_light"]
